AWSTemplateFormatVersion: '2010-09-09'
Description: Recipie Servcie
Globals:
  Api:
    Cors:
      AllowHeaders: '''*'''
      AllowMethods: '''*'''
      AllowOrigin: '''*'''
  Function:
    Environment:
      Variables:
        TABLE_NAME: RecipieTable
    Runtime: nodejs8.10
Outputs:
  RecipieServiceLambda:
    Description: Recipie Lambda Function ARN
    Value:
      Fn::GetAtt:
      - RecipieServiceLambda
      - Arn
Resources:
  RecipieServiceLambda:
    Properties:
      CodeUri: s3://recipies-service/0e98b00a02bb49d26fb62a99c5dde39f
      Events:
        DELETERecipie:
          Properties:
            Method: delete
            Path: /recipie
          Type: Api
        GETRecipie:
          Properties:
            Method: get
            Path: /recipie
          Type: Api
        POSTRecipie:
          Properties:
            Method: post
            Path: /recipie
          Type: Api
        PUTRecipie:
          Properties:
            Method: put
            Path: /recipie
          Type: Api
      Handler: index.lambda_handler
      Policies:
      - AmazonDynamoDBFullAccess
    Type: AWS::Serverless::Function
  RecipieTable:
    Properties:
      PrimaryKey:
        Name: id
        Type: String
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      TableName: RecipieTable
    Type: AWS::Serverless::SimpleTable
Transform: AWS::Serverless-2016-10-31
