AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Recipe Servcie

## #############################################################################
## Parameters
## #############################################################################

Parameters:

    RecipeTableName:
        Type: String
        Default: RecipeTable

## #############################################################################
## Globals
## #############################################################################

Globals:

  Function:
    Runtime: nodejs8.10

## #############################################################################
## Resources
## #############################################################################

Resources:

    # https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    RecipeServiceLambda:
        Type: AWS::Serverless::Function 
        Properties:
            CodeUri: src/
            Handler: index.handler
            # TODO: harden this to read and write only
            Policies: 
                - AmazonDynamoDBFullAccess
            Environment:
                Variables:
                    # QUESTION: do !Ref / !GetAtt not work for environment varables?
                    TABLE_NAME: RecipeTable

    # https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlesssimpletable
    RecipeTable:                   
        Type: AWS::Serverless::SimpleTable
        Properties:
            TableName: 
                Ref: RecipeTableName
            PrimaryKey:
                Name: id
                Type: String
            ProvisionedThroughput:
                ReadCapacityUnits: 5
                WriteCapacityUnits: 5

## #############################################################################
## Outputs
## #############################################################################

Outputs:

    RecipeServiceLambda:
        Description: Recipe Lambda Function ARN
        Value: 
            Fn::GetAtt: RecipeServiceLambda.Arn
        Export:
            Name: RecipeServiceLambda
