AWSTemplateFormatVersion: '2010-09-09'
Description: Recipe Service

## #############################################################################
## Parameters
## #############################################################################

Parameters:

    TableName:
        Type: String  
        Description: the name of the database

    FunctionName:
        Type: String
        Description: the name of the function

    FunctionRuntime:
        Type: String
        Description: lambda function runtime

    SourceBucket:
        Type: String
        Description: lambda function bucket name

    SourceKey:
        Type: String
        Description: lambda function source key

## #############################################################################
## Resources
## #############################################################################

Resources:

    Lambda:
        Type: AWS::Lambda::Function 
        Properties:
            FunctionName:
              Ref: FunctionName
            Runtime:
              Ref: FunctionRuntime
            Code:
              S3Bucket:
                Ref: SourceBucket
              S3Key:
                Ref: SourceKey
            Timeout: 3
            Handler: src/index.handler
            Role: 
                Fn::GetAtt: LambdaExecutionRole.Arn
            Environment:
                Variables:
                    TABLE_NAME:
                        Ref: TableName
            Tags:
                - Key: Project
                  Value: diguiseppe-recipes
                - Key: Stack
                  Value: diguiseppe-recipe-service
                - Key: Environment
                  Value: prod

    # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-iam-role.html
    LambdaExecutionRole:
        Type: AWS::IAM::Role
        Properties:
            AssumeRolePolicyDocument:
                Version: '2012-10-17'
                Statement:
                - Effect: Allow
                  Principal:
                    Service:
                      - lambda.amazonaws.com
                  Action:
                    - sts:AssumeRole
            Path: "/"
            Policies:
                - PolicyName: lambda-crud
                  PolicyDocument:
                    Version: '2012-10-17'
                    Statement:
                        - Effect: Allow
                          Action:
                            - logs:*
                          Resource: arn:aws:logs:*:*:*
                        - Effect: Allow
                          Action:
                            - dynamodb:*
                          Resource:
                            Fn::GetAtt: Table.Arn 
                            
    # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-dynamodb-table.html
    Table:                   
        Type: AWS::DynamoDB::Table
        Properties:
            TableName: 
                Ref: TableName
            AttributeDefinitions:
                - AttributeName: id
                  AttributeType: S
            KeySchema:
                -
                    AttributeName: id
                    KeyType: HASH
            ProvisionedThroughput:
                ReadCapacityUnits: 5
                WriteCapacityUnits: 5
            StreamSpecification:
                StreamViewType: NEW_IMAGE

    # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-lambda-permission.html
    ConfigLambdaPermission:
        Type: "AWS::Lambda::Permission"
        Properties:
            Action: lambda:InvokeFunction
            FunctionName: 
                Ref: Lambda
            Principal: apigateway.amazonaws.com


## #############################################################################
## Outputs
## #############################################################################

Outputs:

    ServiceApiGatewayArn:
        Description: Lambda Function ARN
        Value: 
            Fn::Sub: >-
                arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${Lambda.Arn}/invocations
        # Export:
        #     Name: RecipeServiceApiGatewayArn

    TableStreamArn:
        Description: ARN for Dynamo table stream
        Value: 
            Fn::GetAtt: Table.StreamArn
        # Export:
        #     Name: RecipeTableStreamArn